blueprints/API.py
# -*- Blueprint setup -*-
from os import environ as env
from urllib.parse import unquote_plus
from sanic import Blueprint, response
from packaging.version import parse
from utils.jailbreaks import JailbreakMap as jMap
from utils.device_helper import DeviceMapPG as dMap
from utils.device_helper import DeviceMapPGNamed as aMap
from utils.device_helper import MinVersionMap as minMap
from utils.device_helper import MaxVersionMap as maxMap

APIBP = Blueprint('APIBP', version=1)
validTokens = [t for t in env.get("TOKENS").split("\n")]


# -*- Helper -*-
async def get_parsed_device(device):
    rv = [k for k, v in aMap.items() if device in v]
    if len(rv) == 0:
        return None
    return rv[-1]


# -*- Standard Routes -*-
@APIBP.route('/pls/<device_name>/<iosv>', methods=['GET'])
async def home2(request, device_name, iosv):
    device = unquote_plus(device_name)
    potentialToken = request.headers.get('Authorization')
    if potentialToken is None:
        return response.json({"status": -1})
    else:
        if potentialToken in validTokens:
            potentialDevice = await get_parsed_device(unquote_plus(device))
            if potentialDevice == None:
                return response.json({"status": 1})
            if parse(minMap.get(device)) <= parse(iosv) <= parse(maxMap.get(device)):
                supportedTools = [x for x in jMap if (parse(x.get('minimum_ios')) <= parse(iosv) <= parse(x.get('maximum_ios'))) \
                                  and (dMap.index(x.get('minimum_pg')) <= dMap.index(potentialDevice) <= dMap.index(x.get('maximum_pg')))]
                return response.json(
                    {
                        "status": 0,
                        "jelbreks": supportedTools
                    }
                )
            else:
                return response.json(
                    {
                        "status": 2,
                        "minimum_ios": minMap.get(device),
                        "maximum_ios": maxMap.get(device)
                    }
                )
        else:
            return response.json({"status": -1})

blueprints/general.py
# -*- Blueprint setup -*-
from sanic import Blueprint, response
from sanic.exceptions import NotFound
from packaging.version import parse
from utils.jailbreaks import JailbreakMap as jMap
from utils.device_helper import DeviceMapPG as dMap
from utils.device_helper import MinVersionMap as minMap
from utils.device_helper import MaxVersionMap as maxMap


GeneralBP = Blueprint('GeneralBP')
_tools14 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("14.0") <= parse(x.get('maximum_ios'))]
_tools13 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("13.0") <= parse(x.get('maximum_ios'))]
_tools12 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("12.0") <= parse(x.get('maximum_ios'))]
_tools11 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("11.0") <= parse(x.get('maximum_ios'))]
_tools10 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("10.0") <= parse(x.get('maximum_ios'))]
_tools9 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("9.0") <= parse(x.get('maximum_ios')) or parse("9.0") <= parse(x.get('maximum_ios')) <= parse("9.3.6")]
_tools8 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("8.0") <= parse(x.get('maximum_ios')) or parse("8.0") <= parse(x.get('maximum_ios')) <= parse("8.4")]
_tools7 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("7.0") <= parse(x.get('maximum_ios')) or parse("7.0") <= parse(x.get('maximum_ios')) <= parse("7.1.2")]
_tools6 = [x for x in jMap if parse(x.get('minimum_ios')) <= parse("6.0") <= parse(x.get('maximum_ios')) or parse("6.0") <= parse(x.get('maximum_ios')) <= parse("6.1.6")]


# -*- iPad Name Formatter -*-
async def format_ipad_name(name):
    if name == "iPad Pro 12.9 1":
        return "iPad Pro (12.9) (1.Generation)"
    elif name == "iPad Pro 12.9 2":
        return "iPad Pro (12.9) (2.Generation)"
    elif name == "iPad Pro 12.9 3":
        return "iPad Pro (12.9) (3.Generation)"
    elif name == "iPad Pro 12.9 4":
        return "iPad Pro (12.9) (4.Generation)"
    elif name == "iPad Pro 12.9 5":
        return "iPad Pro (12.9) (5.Generation)"
    elif name == "iPad Pro 11 1":
        return "iPad Pro (11) (1.Generation)"
    elif name == "iPad Pro 11 2":
        return "iPad Pro (11) (2.Generation)"
    elif name == "iPad Pro 11 3":
        return "iPad Pro (11) (3.Generation)"
    else:
        return name


# -*- Standard Routes -*-
@GeneralBP.route('/', methods=['GET'])
async def homepage(request):
    template = request.app.ctx.J2Env.get_template('/pages/Index.jinja2')
    page = await template.render_async(title="Home | Can I Jailbreak 2",
                                       tools14=_tools14,
                                       tools13=_tools13,
                                       tools12=_tools12,
                                       tools11=_tools11,
                                       tools10=_tools10,
                                       tools9=_tools9,
                                       tools8=_tools8,
                                       tools7=_tools7,
                                       tools6=_tools6)
    return response.html(page)


@GeneralBP.route('/guide-me', methods=['GET'])
async def guidance_get(request):
    template = request.app.ctx.J2Env.get_template('/pages/Guide.jinja2')
    page = await template.render_async(title="Jailbreak Wizard | Can I Jailbreak 2",
                                       dValue="5S-iPhone 5S",
                                       ios_version="7.0")
    return response.html(page)


@GeneralBP.route('/guide-me', methods=['POST'])
async def guidance_post(request):
    template = request.app.ctx.J2Env.get_template('/pages/Guide.jinja2')
    deviceName = request.form.get('devicePicker')
    deviceIOS = request.form.get('deviceIOS')
    if deviceName == None or deviceIOS == None:
        page = await template.render_async(title="Jailbreak Wizard | Can I Jailbreak 2",
                                           bannerType=3)
        return response.html(page)
    else:
        bannerType_ = 2
        deviceNameSplit = deviceName.split('-')
        devicePG = deviceNameSplit[0]
        deviceNameFormatted = await format_ipad_name(deviceNameSplit[1])
        if parse(minMap.get(deviceNameFormatted)) <= parse(deviceIOS) <= parse(maxMap.get(deviceNameFormatted)):
            supportedTools = [x for x in jMap if (parse(x.get('minimum_ios')) <= parse(deviceIOS) <= parse(x.get('maximum_ios'))) \
                              and (dMap.index(x.get('minimum_pg')) <= dMap.index(devicePG) <= dMap.index(x.get('maximum_pg')))]
            if len(supportedTools) != 0:
                bannerType_ = 1
            page = await template.render_async(title="Jailbreak Wizard | Can I Jailbreak 2",
                                               bannerType=bannerType_,
                                               jelbreks=supportedTools,
                                               device=deviceNameFormatted,
                                               ios_version=deviceIOS,
                                               dValue='-'.join(deviceNameSplit))
        else:
            page = await template.render_async(title="Jailbreak Wizard | Can I Jailbreak 2",
                                               bannerType=2,
                                               device=deviceNameFormatted,
                                               ios_version=deviceIOS,
                                               dValue='-'.join(deviceNameSplit))
    return response.html(page)


@GeneralBP.route('/tos', methods=['GET'])
async def privacy_policy(request):
    template = request.app.ctx.J2Env.get_template('/pages/Privacy.jinja2')
    page = await template.render_async(title="TOS & Privacy Policy | Can I Jailbreak 2")
    return response.html(page)


@GeneralBP.exception(NotFound)
async def site_exception(request, exception):
    _target = request.path.split('/')[1]
    if _target == 'v1':
        return response.json({"status": -1})
    template = request.app.ctx.J2Env.get_template('/pages/ErrorPage.jinja2')
    page = await template.render_async(title="Holy Papaya! | Can I Jailbreak 2")
    return response.html(page)

templates/_Foundation.jinja2
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ title }}</title>

        <!-- SEO Things (Basic) -->
        <meta name="description" content="Find out if you can jailbreak your iDevice!">
        <meta name="keywords" content="canijailbreak.com, canijailbreak, jailbreak finder, taurine, unc0ver, uncover, ios jailbreak, ios, odyssey, checkrain, checkra1n, canijailbreak2">
        <meta name="author" content="Mirza Saadat Baig">
        <meta name="copyright" content="2020, Mirza Saadat Baig">
        <meta name="robots" content="index,nofollow">

        <!-- SEO Things (OpenGraph) -->
        <meta property="og:name" content="Can I Jailbreak 2">
        <meta property="og:type" content="application.python">
        <meta property="og:description" content="Find out if you can jailbreak your iDevice!">
        <meta property="og:locale" content="en_US">
        <meta property="og:locale:alternate" content="de_DE">
        <meta property="og:site_name" content="Saadat Baig Development">
        <meta property="og:url" content="https://saadat.dev/">

        <!-- SEO Things (Twitter + Others) -->
        <meta name="twitter:creator" content="saadat603">

        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;600;700&family=Open+Sans:wght@300;400;600;700&display=swap" rel="stylesheet">

        <!-- Animate CSS -->
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

        <!-- Icons -->
        <link rel="apple-touch-icon" href="{{ url_for('static', filename='favicons/apple-touch-icon.png') }}">
        <link rel="icon" href="{{ url_for('static', filename='favicons/favicon.ico') }}">

        <!-- Site CSS -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/flatui2.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/cij2.css') }}">

        <!-- Additional CSS -->
        {% block additionalcss %}
        {% endblock %}
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-light navbar-expand-lg bg-white sticky-top">
            <div class="container-fluid">
                <a href="{{ url_for('GeneralBP.homepage') }}" class="navbar-brand mx-auto" style="font-size: 22px; font-weight: bold">
                    Can I Jailbreak 2
                </a>
            </div>
        </nav>

        <!-- Dynamic Content -->
        <div id="contentDiv">
            {% block additionalalert %}
            {% endblock %}
            {% block content %}
            {% endblock %}
        </div>

        <!-- Footer -->
        <div class="footer mt-auto">
            <div class="container-fluid">
                <div class="container">
                    <hr>
                    <div class="row">
                        <div class="col text-center p-1">
                            <div id="contactTwitter">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                                </svg>
                                <a class="small muted" href="https://twitter.com/Saadat603" target="_blank">@saadat603</a>
                            </div>
                        </div>
                        <div class="col text-center p-1">
                            <div id="contactGitHub">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                                </svg>
                                <a class="small" href="https://github.com/mass1ve-err0r/CanIJailbreak2-Website" target="_blank">GitHub</a>
                            </div>
                        </div>
                        <div class="col text-center p-1">
                            <div id="contactGitHub">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-shield-lock-fill" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 0c-.69 0-1.843.265-2.928.56-1.11.3-2.229.655-2.887.87a1.54 1.54 0 0 0-1.044 1.262c-.596 4.477.787 7.795 2.465 9.99a11.777 11.777 0 0 0 2.517 2.453c.386.273.744.482 1.048.625.28.132.581.24.829.24s.548-.108.829-.24a7.159 7.159 0 0 0 1.048-.625 11.775 11.775 0 0 0 2.517-2.453c1.678-2.195 3.061-5.513 2.465-9.99a1.541 1.541 0 0 0-1.044-1.263 62.467 62.467 0 0 0-2.887-.87C9.843.266 8.69 0 8 0zm0 5a1.5 1.5 0 0 1 .5 2.915l.385 1.99a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.99A1.5 1.5 0 0 1 8 5z"/>
                                </svg>
                                <a class="small" href="{{ url_for('GeneralBP.privacy_policy') }}" target="_blank">T.O.S.</a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm text-center p-3">
                            <small class="text-muted">© 2021 <a id="footercr" class="text-muted" href="https://saadat.dev/" target="_blank">Mirza Saadat Baig</a> Development<br>
                                Made with ❤️ in Germany
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- jQuery JS -->
        <script   src="https://code.jquery.com/jquery-3.6.0.slim.js"   integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>

        <!-- Bootstrap JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

        <!-- Additional JS -->
        {% block additionaljs %}
        {% endblock %}
    </body>
</html>

templates/pages/ErrorPage.jinja2
{% extends '_Foundation.jinja2' %}


{% block content %}
    <div class="container pt-2">
        <div style="padding-top: 25%" class="pb-4">
            <div class="card-like-background m-1 p-3">
                <h1 class="card-like-title">You goofball.</h1>
                <div class="text-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-file-earmark-excel-fill" viewBox="0 0 16 16">
                        <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM5.884 6.68 8 9.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 10l2.233 2.68a.5.5 0 0 1-.768.64L8 10.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 10 5.116 7.32a.5.5 0 1 1 .768-.64z"/>
                    </svg>
                    <h5 class="pt-3 pb-2">This is a fairly modern 404, right?</h5>
                </div>
                <div class="row row-cols-1 row-cols-md-2 text-center gy-2">
                    <div class="col d-grid">
                        <a class="btn btn-outline-primary" href="{{ url_for('GeneralBP.homepage') }}" target="_self">
                            Homepage
                        </a>
                    </div>
                    <div class="col d-grid">
                        <a class="btn btn-outline-primary" href="{{ url_for('GeneralBP.guidance_get') }}" target="_self">
                            Jailbreak Wizard
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/Privacy.jinja2
{% extends '_Foundation.jinja2' %}


{% block content %}
    <div class="container pt-2 pb-3">
        <div class="card-like-background m-1 p-3">
            <h1 class="card-like-title">Terms of Service</h1>
            <p>
                CanIJailbreak2 is made free of charge for everyone to use and contribute to.<br>
                <br>
                The (brand-) name "CanIJailbreak2" may <strong>not</strong> be used on forks which include advertisements of any forms.<br>
                Any fork <strong>must</strong> retain the original copyright and linkage to the original author.<br>
            </p>
        </div>
    </div>
    <div class="container pt-2 pb-3">
        <div class="card-like-background m-1 p-3">
            <h1 class="card-like-title">Privacy Policy</h1>
            <p>
                This website <strong>does not</strong> use cookies itself.<br>
                You will however receive a mandatory cookie from Cloudflare. This cookie cannot be used against you.<br>
                <br>
                Enjoy an ad-free experience and even better UX/ UI :-)
            </p>
        </div>
        <div class="row row-cols-1 row-cols-md-2 text-center gy-2 pt-4">
            <div class="col d-grid">
                <a class="btn btn-outline-primary" href="{{ url_for('GeneralBP.homepage') }}" target="_self">
                    Homepage
                </a>
            </div>
            <div class="col d-grid">
                <a class="btn btn-outline-primary" href="{{ url_for('GeneralBP.guidance_get') }}" target="_self">
                    Jailbreak Wizard
                </a>
            </div>
        </div>
    </div>
{% endblock %}